// <auto-generated />
using System;
using ElectricalLearning.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ElectricalLearning.Repositories.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250630052229_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ElectricalLearning.Repositories.Entities.AIRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("AIRequest");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountId = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 6, 30, 5, 22, 28, 944, DateTimeKind.Unspecified).AddTicks(1235), new TimeSpan(0, 0, 0, 0, 0)),
                            ImageUrl = "https://example.com/image1.png",
                            IsDeleted = false,
                            Status = "Pending",
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("ElectricalLearning.Repositories.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("Accounts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 6, 30, 5, 22, 28, 671, DateTimeKind.Unspecified).AddTicks(5743), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "teacher@gmail.com",
                            FullName = "Nguyễn Văn A",
                            IsDeleted = false,
                            PasswordHash = "$2a$11$S1fGBbrZW7mihDufKu/9IOA9nitCS9Gz511FALG2Pe5Qk0jDjJWK.",
                            Role = "Teacher",
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 6, 30, 5, 22, 28, 808, DateTimeKind.Unspecified).AddTicks(8774), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "student@gmail.com",
                            FullName = "Trần Thị B",
                            IsDeleted = false,
                            PasswordHash = "$2a$11$4ZqeabqVOs4mUBkxXWTHF.VZGu43EPtCaHSfwG3JIDQvvPcRstky6",
                            Role = "Student",
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 6, 30, 5, 22, 28, 943, DateTimeKind.Unspecified).AddTicks(7864), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "admin@gmail.com",
                            FullName = "Lê Văn C",
                            IsDeleted = false,
                            PasswordHash = "$2a$11$MuvM24R4cSfrbYfFHU0MP.i.MGCxpUJWEMirKdWJU6I1JldEvXT1e",
                            Role = "Admin",
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("ElectricalLearning.Repositories.Entities.Chapter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GradeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GradeId");

                    b.ToTable("Chapter");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GradeId = 1,
                            IsDeleted = false,
                            Name = "Cơ học"
                        },
                        new
                        {
                            Id = 2,
                            GradeId = 1,
                            IsDeleted = false,
                            Name = "Nhiệt học"
                        },
                        new
                        {
                            Id = 3,
                            GradeId = 2,
                            IsDeleted = false,
                            Name = "Quang học"
                        },
                        new
                        {
                            Id = 4,
                            GradeId = 2,
                            IsDeleted = false,
                            Name = "Âm học"
                        },
                        new
                        {
                            Id = 5,
                            GradeId = 2,
                            IsDeleted = false,
                            Name = "Điện học"
                        },
                        new
                        {
                            Id = 6,
                            GradeId = 3,
                            IsDeleted = false,
                            Name = "Cơ học"
                        },
                        new
                        {
                            Id = 7,
                            GradeId = 3,
                            IsDeleted = false,
                            Name = "Nhiệt học"
                        },
                        new
                        {
                            Id = 8,
                            GradeId = 4,
                            IsDeleted = false,
                            Name = "Điện học"
                        },
                        new
                        {
                            Id = 9,
                            GradeId = 4,
                            IsDeleted = false,
                            Name = "Điện từ học"
                        },
                        new
                        {
                            Id = 10,
                            GradeId = 4,
                            IsDeleted = false,
                            Name = "Quang học"
                        },
                        new
                        {
                            Id = 11,
                            GradeId = 4,
                            IsDeleted = false,
                            Name = "Sự bảo toàn và chuyển hóa năng lượng"
                        },
                        new
                        {
                            Id = 12,
                            GradeId = 5,
                            IsDeleted = false,
                            Name = "Cơ học"
                        },
                        new
                        {
                            Id = 13,
                            GradeId = 5,
                            IsDeleted = false,
                            Name = "Nhiệt học"
                        },
                        new
                        {
                            Id = 14,
                            GradeId = 6,
                            IsDeleted = false,
                            Name = "Điện tích. Điện trường"
                        },
                        new
                        {
                            Id = 15,
                            GradeId = 6,
                            IsDeleted = false,
                            Name = "Dòng điện không đổi"
                        },
                        new
                        {
                            Id = 16,
                            GradeId = 6,
                            IsDeleted = false,
                            Name = "Dòng điện trong các môi trường"
                        },
                        new
                        {
                            Id = 17,
                            GradeId = 6,
                            IsDeleted = false,
                            Name = "Từ trường"
                        },
                        new
                        {
                            Id = 18,
                            GradeId = 6,
                            IsDeleted = false,
                            Name = "Cảm ứng điện từ"
                        },
                        new
                        {
                            Id = 19,
                            GradeId = 6,
                            IsDeleted = false,
                            Name = "Quang học"
                        },
                        new
                        {
                            Id = 20,
                            GradeId = 7,
                            IsDeleted = false,
                            Name = "Dao động cơ"
                        },
                        new
                        {
                            Id = 21,
                            GradeId = 7,
                            IsDeleted = false,
                            Name = "Sóng cơ và sóng âm"
                        },
                        new
                        {
                            Id = 22,
                            GradeId = 7,
                            IsDeleted = false,
                            Name = "Dòng điện xoay chiều"
                        },
                        new
                        {
                            Id = 23,
                            GradeId = 7,
                            IsDeleted = false,
                            Name = "Dao động và sóng điện từ"
                        },
                        new
                        {
                            Id = 24,
                            GradeId = 7,
                            IsDeleted = false,
                            Name = "Sóng ánh sáng"
                        },
                        new
                        {
                            Id = 25,
                            GradeId = 7,
                            IsDeleted = false,
                            Name = "Lượng từ ánh sáng"
                        },
                        new
                        {
                            Id = 26,
                            GradeId = 7,
                            IsDeleted = false,
                            Name = "Hạt nhân nguyên tử"
                        },
                        new
                        {
                            Id = 27,
                            GradeId = 7,
                            IsDeleted = false,
                            Name = "Từ vi mô đến vĩ mô"
                        });
                });

            modelBuilder.Entity("ElectricalLearning.Repositories.Entities.CircuitModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<int?>("ChapterId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("JsonData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("ChapterId");

                    b.HasIndex("LessonId");

                    b.ToTable("CircuitModel");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 6, 30, 5, 22, 28, 944, DateTimeKind.Unspecified).AddTicks(3813), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            JsonData = "{\"resistor\": 100, \"voltage\": 5}",
                            LessonId = 1,
                            Name = "Mạch mẫu 1",
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("ElectricalLearning.Repositories.Entities.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AccountId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("LessonId");

                    b.ToTable("Exercise");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            LessonId = 1,
                            Title = "Một quyển sách nằm yên trên mặt bàn nằm ngang. Hãy xác định các lực tác dụng lên quyển sách, nêu độ lớn và phương chiều của từng lực. Hai lực này có phải là hai lực cân bằng không? Vì sao?"
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            LessonId = 2,
                            Title = "Tại sao khi đun nóng thì các chất rắn, lỏng, khí đều nở ra? Hãy nêu một ví dụ minh họa sự nở vì nhiệt trong đời sống."
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            LessonId = 3,
                            Title = "Giải thích tại sao ta nhìn thấy một vật? Nêu điều kiện để ánh sáng truyền được từ vật đến mắt ta."
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            LessonId = 4,
                            Title = "Thế nào là nguồn âm? Âm phát ra to hay nhỏ phụ thuộc vào yếu tố nào? Độ cao phụ thuộc vào gì?"
                        },
                        new
                        {
                            Id = 5,
                            IsDeleted = false,
                            LessonId = 5,
                            Title = "Khi nối một bóng đèn vào hai cực của pin thì có hiện tượng gì xảy ra? Dòng điện là gì và nó chạy theo chiều nào trong mạch?"
                        },
                        new
                        {
                            Id = 6,
                            IsDeleted = false,
                            LessonId = 6,
                            Title = "Lực ma sát trượt và ma sát nghỉ khác nhau thế nào? Nêu ví dụ minh họa mỗi loại lực ma sát."
                        },
                        new
                        {
                            Id = 7,
                            IsDeleted = false,
                            LessonId = 7,
                            Title = "Nhiệt năng là gì? Có mấy cách làm thay đổi nhiệt năng của một vật? Cho ví dụ."
                        },
                        new
                        {
                            Id = 8,
                            IsDeleted = false,
                            LessonId = 8,
                            Title = "Cho hai bóng đèn mắc nối tiếp và song song vào nguồn điện. Hãy nêu sự khác nhau về độ sáng và ứng dụng của mỗi cách mắc."
                        },
                        new
                        {
                            Id = 9,
                            IsDeleted = false,
                            LessonId = 9,
                            Title = "Lực điện từ là gì? Nêu ứng dụng của lực điện từ trong đời sống hàng ngày."
                        },
                        new
                        {
                            Id = 10,
                            IsDeleted = false,
                            LessonId = 10,
                            Title = "So sánh ảnh tạo bởi thấu kính hội tụ và thấu kính phân kì. Nêu ứng dụng của từng loại thấu kính."
                        },
                        new
                        {
                            Id = 11,
                            IsDeleted = false,
                            LessonId = 11,
                            Title = "Phát biểu định luật bảo toàn năng lượng. Nêu ví dụ minh họa."
                        },
                        new
                        {
                            Id = 12,
                            IsDeleted = false,
                            LessonId = 12,
                            Title = "Thế nào là trọng lực? Nêu biểu thức định luật vạn vật hấp dẫn và ý nghĩa các đại lượng."
                        },
                        new
                        {
                            Id = 13,
                            IsDeleted = false,
                            LessonId = 13,
                            Title = "Nội năng là gì? Trình bày hai cách làm thay đổi nội năng của một vật. Cho ví dụ."
                        },
                        new
                        {
                            Id = 14,
                            IsDeleted = false,
                            LessonId = 14,
                            Title = "Công của lực điện được tính như thế nào? Nêu mối liên hệ giữa công, hiệu điện thế và điện tích."
                        },
                        new
                        {
                            Id = 15,
                            IsDeleted = false,
                            LessonId = 15,
                            Title = "Phát biểu định luật Ôm cho toàn mạch. Viết công thức và giải thích các đại lượng."
                        },
                        new
                        {
                            Id = 16,
                            IsDeleted = false,
                            LessonId = 16,
                            Title = "Nêu sự khác nhau giữa vật liệu dẫn điện và cách điện. Ứng dụng của từng loại."
                        },
                        new
                        {
                            Id = 17,
                            IsDeleted = false,
                            LessonId = 17,
                            Title = "Từ trường là gì? Lực từ tác dụng lên dòng điện có đặc điểm gì? Giải thích hiện tượng nam châm hút sắt."
                        },
                        new
                        {
                            Id = 18,
                            IsDeleted = false,
                            LessonId = 18,
                            Title = "Hiện tượng cảm ứng điện từ là gì? Nêu điều kiện xuất hiện dòng điện cảm ứng."
                        },
                        new
                        {
                            Id = 19,
                            IsDeleted = false,
                            LessonId = 19,
                            Title = "Khúc xạ ánh sáng là gì? Vẽ hình minh họa và nêu định luật khúc xạ ánh sáng."
                        },
                        new
                        {
                            Id = 20,
                            IsDeleted = false,
                            LessonId = 20,
                            Title = "Dao động điều hòa là gì? Nêu đặc điểm và công thức xác định li độ của dao động điều hòa."
                        },
                        new
                        {
                            Id = 21,
                            IsDeleted = false,
                            LessonId = 21,
                            Title = "Sóng cơ là gì? Sóng cơ truyền trong môi trường nào? Nêu ví dụ thực tế."
                        },
                        new
                        {
                            Id = 22,
                            IsDeleted = false,
                            LessonId = 22,
                            Title = "Nêu cấu tạo và nguyên lý hoạt động của mạch điện xoay chiều đơn giản."
                        },
                        new
                        {
                            Id = 23,
                            IsDeleted = false,
                            LessonId = 23,
                            Title = "Mạch dao động gồm những phần tử nào? Trình bày sự biến đổi qua lại giữa điện trường và từ trường."
                        },
                        new
                        {
                            Id = 24,
                            IsDeleted = false,
                            LessonId = 24,
                            Title = "Giao thoa ánh sáng là gì? Nêu điều kiện và ứng dụng trong thực tế."
                        },
                        new
                        {
                            Id = 25,
                            IsDeleted = false,
                            LessonId = 25,
                            Title = "Hiện tượng quang điện trong là gì? Ứng dụng của nó trong các thiết bị điện tử."
                        },
                        new
                        {
                            Id = 26,
                            IsDeleted = false,
                            LessonId = 26,
                            Title = "Tính chất của hạt nhân nguyên tử là gì? Nêu khái niệm đồng vị và phản ứng hạt nhân."
                        },
                        new
                        {
                            Id = 27,
                            IsDeleted = false,
                            LessonId = 27,
                            Title = "Trình bày cấu tạo của vũ trụ theo mô hình hiện đại. Nêu các thành phần chính."
                        });
                });

            modelBuilder.Entity("ElectricalLearning.Repositories.Entities.Formula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CircuitModelId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Expression")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CircuitModelId");

                    b.ToTable("Formula");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CircuitModelId = 1,
                            Description = "Cường độ dòng điện chạy qua dây dẫn tỉ lệ thuận với hiệu điện thế đặt vào hai đầu dây và tỉ lệ nghịch với điện trở của dây.",
                            Expression = "I = U / R",
                            IsDeleted = false,
                            Name = "Định luật Ôm"
                        });
                });

            modelBuilder.Entity("ElectricalLearning.Repositories.Entities.Grade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Name")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Grade");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Name = 6
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            Name = 7
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            Name = 8
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            Name = 9
                        },
                        new
                        {
                            Id = 5,
                            IsDeleted = false,
                            Name = 10
                        },
                        new
                        {
                            Id = 6,
                            IsDeleted = false,
                            Name = 11
                        },
                        new
                        {
                            Id = 7,
                            IsDeleted = false,
                            Name = 12
                        });
                });

            modelBuilder.Entity("ElectricalLearning.Repositories.Entities.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChapterId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.ToTable("Lesson");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChapterId = 1,
                            IsDeleted = false,
                            Title = "Lực - Hai lực cân bằng"
                        },
                        new
                        {
                            Id = 2,
                            ChapterId = 2,
                            IsDeleted = false,
                            Title = "Sự nở vì nhiệt"
                        },
                        new
                        {
                            Id = 3,
                            ChapterId = 3,
                            IsDeleted = false,
                            Title = "Sự truyền ánh sáng"
                        },
                        new
                        {
                            Id = 4,
                            ChapterId = 4,
                            IsDeleted = false,
                            Title = "Nguồn âm - Độ to, độ cao của âm"
                        },
                        new
                        {
                            Id = 5,
                            ChapterId = 5,
                            IsDeleted = false,
                            Title = "Dòng điện - nguồn điện"
                        },
                        new
                        {
                            Id = 6,
                            ChapterId = 6,
                            IsDeleted = false,
                            Title = "Lực ma sát"
                        },
                        new
                        {
                            Id = 7,
                            ChapterId = 7,
                            IsDeleted = false,
                            Title = "Nhiệt năng"
                        },
                        new
                        {
                            Id = 8,
                            ChapterId = 8,
                            IsDeleted = false,
                            Title = "Đoạn mạch nối tiếp - Đoạn mạch song song"
                        },
                        new
                        {
                            Id = 9,
                            ChapterId = 9,
                            IsDeleted = false,
                            Title = "Lực điện từ"
                        },
                        new
                        {
                            Id = 10,
                            ChapterId = 10,
                            IsDeleted = false,
                            Title = "Thấu kính hội tụ - Thấu kính phân kì"
                        },
                        new
                        {
                            Id = 11,
                            ChapterId = 11,
                            IsDeleted = false,
                            Title = "Định luật bảo toàn năng lượng"
                        },
                        new
                        {
                            Id = 12,
                            ChapterId = 12,
                            IsDeleted = false,
                            Title = "Lực hấp dẫn - Định luật vạn vật hấp dẫn"
                        },
                        new
                        {
                            Id = 13,
                            ChapterId = 13,
                            IsDeleted = false,
                            Title = "Nội năng và sự biến thiên nội năng"
                        },
                        new
                        {
                            Id = 14,
                            ChapterId = 14,
                            IsDeleted = false,
                            Title = "Công của lực điện - Điện thế. Hiệu điện thế"
                        },
                        new
                        {
                            Id = 15,
                            ChapterId = 15,
                            IsDeleted = false,
                            Title = "Định luật Ôm đối với toàn mạch"
                        },
                        new
                        {
                            Id = 16,
                            ChapterId = 16,
                            IsDeleted = false,
                            Title = "Dòng điện trong các vật liệu"
                        },
                        new
                        {
                            Id = 17,
                            ChapterId = 17,
                            IsDeleted = false,
                            Title = "Từ trường - Lực từ. Cảm ứng từ"
                        },
                        new
                        {
                            Id = 18,
                            ChapterId = 18,
                            IsDeleted = false,
                            Title = "Từ thông. Cảm ứng điện từ"
                        },
                        new
                        {
                            Id = 19,
                            ChapterId = 19,
                            IsDeleted = false,
                            Title = "Khúc xạ ánh sáng"
                        },
                        new
                        {
                            Id = 20,
                            ChapterId = 20,
                            IsDeleted = false,
                            Title = "Dao động điều hòa"
                        },
                        new
                        {
                            Id = 21,
                            ChapterId = 21,
                            IsDeleted = false,
                            Title = "Sóng cơ và sự truyền sóng cơ"
                        },
                        new
                        {
                            Id = 22,
                            ChapterId = 22,
                            IsDeleted = false,
                            Title = "Các mạch điện xoay chiều"
                        },
                        new
                        {
                            Id = 23,
                            ChapterId = 23,
                            IsDeleted = false,
                            Title = "Mạch dao động - Điện từ trường"
                        },
                        new
                        {
                            Id = 24,
                            ChapterId = 24,
                            IsDeleted = false,
                            Title = "Giao thoa ánh sáng"
                        },
                        new
                        {
                            Id = 25,
                            ChapterId = 25,
                            IsDeleted = false,
                            Title = "Hiện tượng quang điện trong"
                        },
                        new
                        {
                            Id = 26,
                            ChapterId = 26,
                            IsDeleted = false,
                            Title = "Tính chất và cấu tạo hạt nhân"
                        },
                        new
                        {
                            Id = 27,
                            ChapterId = 27,
                            IsDeleted = false,
                            Title = "Cấu tạo vũ trụ"
                        });
                });

            modelBuilder.Entity("ElectricalLearning.Repositories.Entities.Submission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("ExerciseId");

                    b.ToTable("Submission");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountId = 2,
                            Answer = "Có hai lực tác dụng lên quyển sách: trọng lực hướng xuống và lực nâng của mặt bàn hướng lên. Hai lực này có cùng độ lớn, cùng phương, ngược chiều nên là hai lực cân bằng. Vì sách nằm yên nên tổng hợp lực tác dụng bằng 0.",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 6, 30, 5, 22, 28, 944, DateTimeKind.Unspecified).AddTicks(8043), new TimeSpan(0, 0, 0, 0, 0)),
                            ExerciseId = 1,
                            IsDeleted = false,
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 2,
                            AccountId = 2,
                            Answer = "Khi đun nóng, các phân tử chuyển động mạnh hơn, làm tăng khoảng cách giữa chúng nên vật nở ra. Ví dụ: dây điện chùng xuống vào buổi trưa do bị nở vì nhiệt.",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 6, 30, 5, 22, 28, 944, DateTimeKind.Unspecified).AddTicks(8055), new TimeSpan(0, 0, 0, 0, 0)),
                            ExerciseId = 2,
                            IsDeleted = false,
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 3,
                            AccountId = 2,
                            Answer = "Vì vật phát ra ánh sáng hoặc phản xạ ánh sáng từ nguồn sáng. Ánh sáng phải truyền đến mắt ta theo đường thẳng trong môi trường trong suốt.",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 6, 30, 5, 22, 28, 944, DateTimeKind.Unspecified).AddTicks(8056), new TimeSpan(0, 0, 0, 0, 0)),
                            ExerciseId = 3,
                            IsDeleted = false,
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 4,
                            AccountId = 2,
                            Answer = "Nguồn âm là vật dao động tạo ra âm thanh. Độ to phụ thuộc biên độ dao động, độ cao phụ thuộc tần số dao động.",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 6, 30, 5, 22, 28, 944, DateTimeKind.Unspecified).AddTicks(8058), new TimeSpan(0, 0, 0, 0, 0)),
                            ExerciseId = 4,
                            IsDeleted = false,
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 5,
                            AccountId = 2,
                            Answer = "Đèn sáng chứng tỏ có dòng điện chạy trong mạch. Dòng điện là dòng chuyển dời có hướng của các electron tự do, chạy từ cực âm sang cực dương ngoài mạch.",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 6, 30, 5, 22, 28, 944, DateTimeKind.Unspecified).AddTicks(8059), new TimeSpan(0, 0, 0, 0, 0)),
                            ExerciseId = 5,
                            IsDeleted = false,
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 6,
                            AccountId = 2,
                            Answer = "Lực ma sát trượt xuất hiện khi vật trượt, ma sát nghỉ khi vật chịu lực nhưng chưa trượt. Ví dụ: kéo rương nặng trên sàn (trượt), bàn nằm yên dù bị đẩy nhẹ (nghỉ).",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 6, 30, 5, 22, 28, 944, DateTimeKind.Unspecified).AddTicks(8062), new TimeSpan(0, 0, 0, 0, 0)),
                            ExerciseId = 6,
                            IsDeleted = false,
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 7,
                            AccountId = 2,
                            Answer = "Nhiệt năng là tổng động năng của các phân tử. Có thể thay đổi qua thực hiện công hoặc truyền nhiệt. Ví dụ: cọ xát hai tay tạo nhiệt.",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 6, 30, 5, 22, 28, 944, DateTimeKind.Unspecified).AddTicks(8064), new TimeSpan(0, 0, 0, 0, 0)),
                            ExerciseId = 7,
                            IsDeleted = false,
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 8,
                            AccountId = 2,
                            Answer = "Nối tiếp: cùng dòng, điện áp chia nhỏ, đèn yếu hơn. Song song: mỗi nhánh cùng điện áp, sáng hơn. Song song được dùng phổ biến hơn.",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 6, 30, 5, 22, 28, 944, DateTimeKind.Unspecified).AddTicks(8065), new TimeSpan(0, 0, 0, 0, 0)),
                            ExerciseId = 8,
                            IsDeleted = false,
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 9,
                            AccountId = 2,
                            Answer = "Lực điện từ là lực giữa các điện tích chuyển động. Ứng dụng: động cơ điện, loa, máy biến áp, chuông điện.",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 6, 30, 5, 22, 28, 944, DateTimeKind.Unspecified).AddTicks(8067), new TimeSpan(0, 0, 0, 0, 0)),
                            ExerciseId = 9,
                            IsDeleted = false,
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 10,
                            AccountId = 2,
                            Answer = "Thấu kính hội tụ: ảnh thật/ngược/lớn hơn; phân kì: ảnh ảo/cùng chiều/nhỏ hơn. Hội tụ: máy ảnh, kính lúp; phân kì: kính cận.",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 6, 30, 5, 22, 28, 944, DateTimeKind.Unspecified).AddTicks(8069), new TimeSpan(0, 0, 0, 0, 0)),
                            ExerciseId = 10,
                            IsDeleted = false,
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 11,
                            AccountId = 2,
                            Answer = "Tổng năng lượng không đổi trong một hệ cô lập. Ví dụ: con lắc chuyển từ thế năng sang động năng và ngược lại.",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 6, 30, 5, 22, 28, 944, DateTimeKind.Unspecified).AddTicks(8071), new TimeSpan(0, 0, 0, 0, 0)),
                            ExerciseId = 11,
                            IsDeleted = false,
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 12,
                            AccountId = 2,
                            Answer = "Trọng lực là lực hút của Trái Đất. F = G*(m1*m2)/r^2, với G là hằng số hấp dẫn, m là khối lượng, r là khoảng cách.",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 6, 30, 5, 22, 28, 944, DateTimeKind.Unspecified).AddTicks(8072), new TimeSpan(0, 0, 0, 0, 0)),
                            ExerciseId = 12,
                            IsDeleted = false,
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 13,
                            AccountId = 2,
                            Answer = "Nội năng là tổng động năng và thế năng vi mô. Thay đổi bằng truyền nhiệt hoặc thực hiện công. Ví dụ: đun nước, nén khí.",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 6, 30, 5, 22, 28, 944, DateTimeKind.Unspecified).AddTicks(8073), new TimeSpan(0, 0, 0, 0, 0)),
                            ExerciseId = 13,
                            IsDeleted = false,
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 14,
                            AccountId = 2,
                            Answer = "A = qU, với A là công, q là điện tích, U là hiệu điện thế. Công lực điện tỉ lệ thuận với U và q.",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 6, 30, 5, 22, 28, 944, DateTimeKind.Unspecified).AddTicks(8074), new TimeSpan(0, 0, 0, 0, 0)),
                            ExerciseId = 14,
                            IsDeleted = false,
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 15,
                            AccountId = 2,
                            Answer = "I = E / (R + r), với I là cường độ dòng điện, E là suất điện động, R là điện trở ngoài, r là điện trở trong nguồn.",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 6, 30, 5, 22, 28, 944, DateTimeKind.Unspecified).AddTicks(8076), new TimeSpan(0, 0, 0, 0, 0)),
                            ExerciseId = 15,
                            IsDeleted = false,
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 16,
                            AccountId = 2,
                            Answer = "Dẫn điện: kim loại (đồng, nhôm), dùng làm dây dẫn. Cách điện: nhựa, sứ, dùng bọc cách điện.",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 6, 30, 5, 22, 28, 944, DateTimeKind.Unspecified).AddTicks(8077), new TimeSpan(0, 0, 0, 0, 0)),
                            ExerciseId = 16,
                            IsDeleted = false,
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 17,
                            AccountId = 2,
                            Answer = "Từ trường là vùng không gian có lực từ. Lực từ vuông góc với dòng điện và từ trường. Nam châm hút sắt vì tạo từ trường mạnh.",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 6, 30, 5, 22, 28, 944, DateTimeKind.Unspecified).AddTicks(8078), new TimeSpan(0, 0, 0, 0, 0)),
                            ExerciseId = 17,
                            IsDeleted = false,
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 18,
                            AccountId = 2,
                            Answer = "Là hiện tượng xuất hiện dòng điện cảm ứng khi từ thông qua mạch kín biến đổi. Điều kiện: thay đổi từ trường qua mạch kín.",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 6, 30, 5, 22, 28, 944, DateTimeKind.Unspecified).AddTicks(8079), new TimeSpan(0, 0, 0, 0, 0)),
                            ExerciseId = 18,
                            IsDeleted = false,
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 19,
                            AccountId = 2,
                            Answer = "Là sự đổi hướng truyền ánh sáng khi truyền qua mặt phân cách hai môi trường. Định luật: sin(i)/sin(r) = n2/n1.",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 6, 30, 5, 22, 28, 944, DateTimeKind.Unspecified).AddTicks(8080), new TimeSpan(0, 0, 0, 0, 0)),
                            ExerciseId = 19,
                            IsDeleted = false,
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 20,
                            AccountId = 2,
                            Answer = "Dao động điều hòa có li độ: x = A cos(ωt + φ). Đặc điểm: tuần hoàn, biên độ không đổi, tần số xác định.",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 6, 30, 5, 22, 28, 944, DateTimeKind.Unspecified).AddTicks(8081), new TimeSpan(0, 0, 0, 0, 0)),
                            ExerciseId = 20,
                            IsDeleted = false,
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 21,
                            AccountId = 2,
                            Answer = "Sóng cơ là dao động lan truyền trong môi trường vật chất. Không truyền được trong chân không. Ví dụ: sóng âm trong không khí.",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 6, 30, 5, 22, 28, 944, DateTimeKind.Unspecified).AddTicks(8083), new TimeSpan(0, 0, 0, 0, 0)),
                            ExerciseId = 21,
                            IsDeleted = false,
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 22,
                            AccountId = 2,
                            Answer = "Gồm nguồn xoay chiều, điện trở, cuộn cảm, tụ điện. Nguyên lý: dòng điện thay đổi tuần hoàn theo thời gian.",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 6, 30, 5, 22, 28, 944, DateTimeKind.Unspecified).AddTicks(8084), new TimeSpan(0, 0, 0, 0, 0)),
                            ExerciseId = 22,
                            IsDeleted = false,
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 23,
                            AccountId = 2,
                            Answer = "Gồm cuộn cảm L và tụ điện C. Năng lượng dao động giữa điện trường và từ trường, tạo dao động điện từ.",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 6, 30, 5, 22, 28, 944, DateTimeKind.Unspecified).AddTicks(8085), new TimeSpan(0, 0, 0, 0, 0)),
                            ExerciseId = 23,
                            IsDeleted = false,
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 24,
                            AccountId = 2,
                            Answer = "Là sự tăng cường hay triệt tiêu ánh sáng khi chồng lấp hai sóng đồng bộ. Ứng dụng: đo bước sóng, kỹ thuật quang.",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 6, 30, 5, 22, 28, 944, DateTimeKind.Unspecified).AddTicks(8086), new TimeSpan(0, 0, 0, 0, 0)),
                            ExerciseId = 24,
                            IsDeleted = false,
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 25,
                            AccountId = 2,
                            Answer = "Hiện tượng chất bán dẫn tạo dòng điện khi được chiếu sáng. Ứng dụng: pin mặt trời, cảm biến ánh sáng.",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 6, 30, 5, 22, 28, 944, DateTimeKind.Unspecified).AddTicks(8087), new TimeSpan(0, 0, 0, 0, 0)),
                            ExerciseId = 25,
                            IsDeleted = false,
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 26,
                            AccountId = 2,
                            Answer = "Hạt nhân gồm proton và neutron. Đồng vị là nguyên tử cùng số proton khác neutron. Phản ứng hạt nhân: phân hạch, nhiệt hạch.",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 6, 30, 5, 22, 28, 944, DateTimeKind.Unspecified).AddTicks(8102), new TimeSpan(0, 0, 0, 0, 0)),
                            ExerciseId = 26,
                            IsDeleted = false,
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 27,
                            AccountId = 2,
                            Answer = "Vũ trụ gồm thiên hà, sao, hành tinh, vật chất tối. Mô hình hiện đại cho thấy vũ trụ đang giãn nở từ vụ nổ Big Bang.",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 6, 30, 5, 22, 28, 944, DateTimeKind.Unspecified).AddTicks(8104), new TimeSpan(0, 0, 0, 0, 0)),
                            ExerciseId = 27,
                            IsDeleted = false,
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("ElectricalLearning.Repositories.Entities.AIRequest", b =>
                {
                    b.HasOne("ElectricalLearning.Repositories.Entities.Account", "Account")
                        .WithMany("AIRequests")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("ElectricalLearning.Repositories.Entities.Chapter", b =>
                {
                    b.HasOne("ElectricalLearning.Repositories.Entities.Grade", "Grade")
                        .WithMany("Chapters")
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grade");
                });

            modelBuilder.Entity("ElectricalLearning.Repositories.Entities.CircuitModel", b =>
                {
                    b.HasOne("ElectricalLearning.Repositories.Entities.Account", "Account")
                        .WithMany("CircuitModels")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElectricalLearning.Repositories.Entities.Chapter", null)
                        .WithMany("CircuitModels")
                        .HasForeignKey("ChapterId");

                    b.HasOne("ElectricalLearning.Repositories.Entities.Lesson", "Lesson")
                        .WithMany("CircuitModels")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("ElectricalLearning.Repositories.Entities.Exercise", b =>
                {
                    b.HasOne("ElectricalLearning.Repositories.Entities.Account", null)
                        .WithMany("Exercises")
                        .HasForeignKey("AccountId");

                    b.HasOne("ElectricalLearning.Repositories.Entities.Lesson", "Lesson")
                        .WithMany("Exercises")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("ElectricalLearning.Repositories.Entities.Formula", b =>
                {
                    b.HasOne("ElectricalLearning.Repositories.Entities.CircuitModel", "CircuitModel")
                        .WithMany("Formulas")
                        .HasForeignKey("CircuitModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CircuitModel");
                });

            modelBuilder.Entity("ElectricalLearning.Repositories.Entities.Lesson", b =>
                {
                    b.HasOne("ElectricalLearning.Repositories.Entities.Chapter", "Chapter")
                        .WithMany()
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chapter");
                });

            modelBuilder.Entity("ElectricalLearning.Repositories.Entities.Submission", b =>
                {
                    b.HasOne("ElectricalLearning.Repositories.Entities.Account", "Account")
                        .WithMany("Submissions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElectricalLearning.Repositories.Entities.Exercise", "Exercise")
                        .WithMany("Submissions")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("ElectricalLearning.Repositories.Entities.Account", b =>
                {
                    b.Navigation("AIRequests");

                    b.Navigation("CircuitModels");

                    b.Navigation("Exercises");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("ElectricalLearning.Repositories.Entities.Chapter", b =>
                {
                    b.Navigation("CircuitModels");
                });

            modelBuilder.Entity("ElectricalLearning.Repositories.Entities.CircuitModel", b =>
                {
                    b.Navigation("Formulas");
                });

            modelBuilder.Entity("ElectricalLearning.Repositories.Entities.Exercise", b =>
                {
                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("ElectricalLearning.Repositories.Entities.Grade", b =>
                {
                    b.Navigation("Chapters");
                });

            modelBuilder.Entity("ElectricalLearning.Repositories.Entities.Lesson", b =>
                {
                    b.Navigation("CircuitModels");

                    b.Navigation("Exercises");
                });
#pragma warning restore 612, 618
        }
    }
}
